Team2-Project-OpenMind/OpenMind_Team2

src/api/api.answers.js, src/api/api.questions.js, src/api/api.subjects.js, src/api/domain.js
=> Api setting

src/api/api.answers.js, src/api/api.questions.js, src/api/api.subjects.js
=> Feat(api): api method 추가 및 수정

src/components/feed/Card.js, src/components/feed/CardStyle.js, src/components/layout/Banner.js, src/components/layout/index.js, src/pages/post/PostContainer.js, src/pages/post/PostStyle.js
=> Post card 스타일링

public/index.html, src/components/ModalPortal.js, src/pages/post/PostContainer.js
=> Feat(PostContainer.js) : createPortal 구현

src/App.js, src/components/modal/PopOverMenu.js, src/components/modal/questionModal.js, src/pages/answer/AnswerContainer.js, src/pages/post/PostContainer.js
=> question Modal Id값 수정

src/App.js, src/api/api.answers.js, src/components/answerFeedCard/FeedCard.js, src/components/modal/PopOverMenu.js, src/pages/answer/AnswerContainer.js
Feat(PopOverMenu.js): 팝오버 기능  구현 완료
=> Feat(PopOverMenu.js): 팝오버 기능  구현 완료

src/components/Header.js, src/components/listPageCard/CardListStyle.js, src/components/modal/questionModal.js, src/components/pagination/PaginationStyle.js, src/pages/answer/AnswerContainer.js, src/pages/list/ListStyle.js, src/pages/post/PostContainer.js, src/pages/post/PostStyle.js
파일명 소문자-> 대문자, 모달 배경 누르면 꺼지는 기능 추가
=> 파일명 소문자-> 대문자, 모달 배경 누르면 꺼지는 기능 추가

src/App.js, src/pages/answer/AnswerContainer.js, src/pages/post/PostContainer.js
=> 답변페이지 라우팅 경로 수정, 답변페이지 userId 받아오는 부분 추가

public/index.html, src/components/SNSshare.js, src/pages/post/PostContainer.js, src/utils/CopyToClipboard.js, src/utils/KakaoSDK.js, src/utils/Login.js, src/utils/LoginCheck.js
=> SNS 공유 기능, 링크복사 기능 구현

src/components/answerFeedCard/FeedCard.js, src/components/feed/FeedCardItem.js, src/components/modal/PopOverMenu.js, src/pages/answer/AnswerContainer.js
- 이미 답변이 있는 경우 POST 요청을 보내지 못하는 문제가 있었음
- 따라서 이미 답변이 있는 경우에는 PATCH를 통해 수정하게 하기
- POST 보낼 때 사용자가 조금 더 납득하기 쉬운 유저플로우를 구현하기 위해 프롬프트 기능 추가
useEffect를 통해 바로 값이 반영되게 변경(현재는 새로고침을 해야만 적용)
=> PopOverMenu 수정

src/components/answerFeedCard/FeedCard.js, src/components/answerFeedCard/FeedCardStyled.js, src/pages/answer/AnswerContainer.js
Fix(FeedCard.js) : 답변 완료 및 수정 기능 개선
=> feat(FeedCard.js): 답변자 프로필이미지 및 이름 GET 함수로 구현

src/components/feed/FeedCardItem.js, src/components/feed/FeedCardStyle.js, src/pages/answer/AnswerContainer.js
=> 좋아요 싫어요 기능 구현 완료

src/components/answerFeedCard/FeedCard.js, src/components/modal/PopOverMenu.js, src/pages/answer/AnswerContainer.js, src/pages/post/PostContainer.js
=> PopOverMenu 기능 수정

src/components/modal/PopOverMenu.js
=>  handleDeleteQuestion 작동 후 렌더링 안 되는 문제 해결

src/pages/answer/AnswerContainer.js
Fix(AnswerContainer.js) : PopOverMenu close 기능 수정
=> Fix(AnswerContainer.js) : PopOverMenu close 기능 수정

src/components/modal/PopOverMenu.js, src/pages/answer/AnswerContainer.js
Feat(AnswerContainer.js) : PopOverMenu 외부 클릭시 팝업창 꺼지게 구현
Fix(AnswerContainer.js) : 전체삭제 기능 내 아규먼트 수정, 재가동
=> Feat(AnswerContainer.js) : PopOverMenu 외부 클릭시 팝업창 꺼지게 구현

src/components/MusicBar.js, src/components/ThemeToggleButton.js, src/components/layout/index.js
=> Feat(BGM): 추가기능 BGM 구현 완료

src/App.js, src/pages/PageNotFound.js
1. Page Not Found 처리
- /wrong-route -> /wrong-route (No redirection)
- 로고 클릭으로 home으로 이동 가능한 404 페이지 렌더링
2. 리다이렉션 처리
- /list/wrong-route -> /list
- /post/id/wrong-route -> /post
- /post/id/answer/wrong-route -> /post/id/answer
=> Feat(App.js, PageNotFound.js): Page Not Found & 리다이렉션 구현

package-lock.json, package.json, src/components/Youtube.js, src/components/answerFeedCard/Reply.js, src/components/feed/FeedCardItem.js, src/components/feed/FeedCardList.js, src/components/modal/PopOverMenu.js, src/components/modal/QuestionModal.js, src/pages/answer/AnswerContainer.js, src/pages/post/PostContainer.js, src/utils/ExtractYoutubeId.js
questionModal 내 이름, 이미지 가져오기, Youtube 임베디드 기능 추가 
유튜브 임베디드 기능 추가후 콘솔에 이런오류가 뜨는데.. 영상은 잘 뜹니다..! 내일 한 번 더 확인해보겠습니당
=> questionModal 내 이름, 이미지 가져오기, Youtube 임베디드 기능 추가 

src/components/feed/FeedCardItem.js, src/pages/post/PostContainer.js
ㄴ 전체 데이터 리렌더링 대신 FeedCardItem 컴포넌트에서 state를 화면에 보여주는 방법으로 변경
=> Feat(FeedCardItem): 좋아요, 싫어요 기능 수정

package-lock.json, package.json, src/components/UserNameInHeader.js, src/components/Youtube.js, src/components/answerFeedCard/Reply.js, src/components/feed/FeedCardItem.js, src/components/modal/PopOverMenu.js, src/components/modal/QuestionModal.js, src/pages/answer/AnswerContainer.js, src/utils/ExtractYoutubeId.js
컴포넌트 정리 필요없는 주석/console.log 삭제, 사용 라이브러리 react-youtube서 react-player로 변경
=> 컴포넌트 정리 필요없는 주석 삭제, 사용 라이브러리 react-youtube서 react-player로 변경

src/components/modal/PopOverMenu.js
HotFix(PopOverMenu.js) : 오류 해결
=> HotFix(PopOverMenu.js) : 오류 해결

src/components/modal/PopOverMenu.js, src/pages/answer/AnswerContainer.js, src/pages/answer/AnswerStyle.js
=> Chore() : PopOver상황공유용 세팅

src/components/feed/FeedCardItem.js, src/components/feed/FeedCardStyle.js, src/hooks/useIntersect.js, src/pages/post/PostContainer.js, src/pages/post/PostStyle.js
=> Post card - 질문피드 보기 옵션 추가 및 좋아요/싫어요 수정

src/components/BGMbutton.js
=> Fix(BGMbutton): 작성완료시 노래 나오는 이슈 해결

src/components/answerFeedCard/FeedCardMainContent.js, src/components/answerFeedCard/FeedCardStyled.js, src/components/feed/FeedCardItem.js
Fix(FeedCardItem.js) : 유튜브 플레이어 반응형 설정
=> Fix(FeedCardItem.js) : 유튜브 플레이어 반응형 설정

src/pages/post/PostStyle.js, src/utils/Login.js
=> Dev to main
